version: '3.8'

services:
    nginx:
        depends_on:
            - server
        restart: always
        image: nginx
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: 'nginx'
        ports:
            - '80:80'
            # - '443:443'
            
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'server'
        volumes:
            - .:/usr/src/server/
            - '/usr/src/server/node_modules'
        working_dir: /usr/src/server
        command: sh -c "yarn && yarn build && yarn start bypass"
        ports:
            - 3001:3001
            - 3002:3002